Homework 2
SASHKEVICH/MovieQuiz-ios pull request #2
Opened 2022-10-16 09:31 UTC by SASHKEVICH

2022-10-16 12:19 UTC, mmbabaev requested changes

2022-10-16 12:19 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private func isLastQuestion() -> Bool {
можно сделать вычисляемым свойством
`var isLastQuestion: Bool`

2022-10-16 12:19 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let vm = convert(model: currentQuestion)
рекомендую не сокращать особо `let viewModel`

2022-10-16 12:19 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
Если быстро нажимать одну и ту же кнопку, то срабатывают лишние нажатия, пока мы ожидаем следующего вопроса. Чтобы этого не было, можно использовать свойство isEnabled. При начале ожидания "выключать" кнопку, после ожидания "включать" https://developer.apple.com/documentation/uikit/uicontrol/1618217-isenabled

2022-10-17 05:13 UTC, SASHKEVICH commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private func isLastQuestion() -> Bool {
Забываю, что так можно сделать, поэтому по привычке пишу методом))

2022-10-17 05:14 UTC, SASHKEVICH commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
Я еще там добавил анимацию, чтобы плавно менялся цвет заднего фона у кнопки, что мол она неактивна. Спасибо за подсказку))

2022-10-17 13:24 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        UIView.animate(withDuration: 0.5, delay: 0.0, animations: {
интересно

2022-10-18 04:13 UTC, merged