sprint 5
SASHKEVICH/MovieQuiz-ios pull request #3
Opened 2022-10-29 16:14 UTC by SASHKEVICH

Домашняя работа пятого спринта

2022-10-30 13:55 UTC, SASHKEVICH commented on MovieQuiz.xcodeproj/project.pbxproj
> +		961CA6EF290D674C005855F4 /* StatisticService.swift in Sources */ = {isa = PBXBuildFile; fileRef = 961CA6EE290D674C005855F4 /* StatisticService.swift */; };
На всякий пожарный закоммитил этот файл, чтобы случайно проект не поломался :)

2022-10-30 15:25 UTC, ABashkirova requested changes
Привет!

Все с работой хорошо, кроме подсчета количества игр, также остались баги с версткой. 

Цвет фона главного экрана, content mode у ланч скрина, скругление при старте у постера – нужно исправить. Также кнопки не прилипают к низу safe area (зажать cmd в фигме, чтобы проверить расстояние до безопасной области). 

Нужно также доправить

2022-10-30 15:25 UTC, ABashkirova commented on MovieQuiz/Helpers/Date+Formatting.swift
> +        return formatter.string(from: self)
На сколько помню, в исходниках уже был код форматтера. В чем отличие – там был статически задан форматер, инициализация происходила раз за обращение. 

В вашем случае форматер будет создаваться каждый раз при обращении. Это не очень оптимально, потому что создание форматтера дорогая операция. Больше [тут](https://sarunw.com/posts/how-expensive-is-dateformatter/)

2022-10-30 15:25 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            }
if с ретурном – не swifty код, если уж хочется в таком стиле писать, то используйте guard 

или лучше честный if-else

2022-10-30 15:25 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        correctAnswers = 0
я бы сбрасывала состояние полностью после нажатия на кнопку, так сохраняется атомарность транзакции

2022-10-30 15:25 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let data = jsonString.data(using: .utf8)!
1) этот код из дополнительно задания, его стоило выполнять в отдельной ветке. Сейчас неиспользуется, поэтому должен быть удален
2) В учебных материалах, гайдах для простоты донесения сути используют force unwrap. Не используете его в своих работах, которые собираетесь показывать в портфолио. Всегда честно разыменовывайте результат опциональных функций

2022-10-30 15:25 UTC, ABashkirova commented on MovieQuiz/Services/StatisticService.swift
> +
для примитивов в userDefaults уже есть специальные функции integer, double, float, bool. Гораздо дешевле использовать их

2022-10-30 15:25 UTC, ABashkirova commented on MovieQuiz/Services/StatisticService.swift
> +                  return -1
В первый раз сработает неверно, и количество сыгранных игр будет неверно считать

здесь нужен ноль

2022-10-30 15:35 UTC, SASHKEVICH commented on MovieQuiz/Helpers/Date+Formatting.swift
> +        return formatter.string(from: self)
Совсем не увидел файлик Date+Extensions.swift))) Спасибо за подсказку и за статью <3

2022-10-31 07:53 UTC, ABashkirova commented
Не могу понять на какой вопрос надо отвечать. Давайте поправим верстку 
- у главного стека внизу должен быть констрейнт 0 от safe area
- тексту вопроса не смотря на верстку, надо дать больше пространства, уменьшить значения констрейнтов 

<img width="538" alt="Screenshot 2022-10-31 at 11 51 36" src="https://user-images.githubusercontent.com/20269264/198958289-5696b43e-cf5f-4840-bbd5-5a139f596ea4.png">

2022-10-31 18:25 UTC, ABashkirova approved these changes
Работа принята, спасибо!

2022-11-01 16:54 UTC, merged

2022-11-12 15:42 UTC, SASHKEVICH commented
@ABashkirova Александра, здравствуйте! Я не вижу Ваших комментариев на ПР спринта №6...