sprint 6
SASHKEVICH/MovieQuiz-ios pull request #4
Opened 2022-11-11 16:10 UTC by SASHKEVICH

2022-11-12 15:49 UTC, ABashkirova requested changes
Прошу прощения :( иногда не прожимается ревью.

2022-11-12 15:49 UTC, ABashkirova commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
Обращу внимание на свойство `errorMessage`. 

Здесь может прийти текст с ошибкой, в таком случае сервис обычно возвращает пустой список фильмов `items`. С пустым списком приложение будет выглядеть сломанным. Это состояние называют краевым случаем, его стоит обрабатывать как ошибку, например, показывать алерт.
С точки зрения проектирования API сервиса IMDB, эту ошибку лучше вернуть c кодом ошибки клиента ([группа 4хх](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses)). Но случается и так, что ответ имеет статус код 200, а тело ответа содержит сообщение об ошибке, как в нашем примере. Такой ответ в любом случае необходимо обработать разработчику фронтенда (web, iOS, android).

 **Примеры состояний, когда такое происходит:**

- API key неверный
- API key просрочен
- количество запросов в день превышено (по документации не больше 100)

2022-11-12 15:49 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        showLoadingIndicator()
Возможно так показали в уроке, здесь это не принципиально, но обычно принято сразу начать крутить лоадер, а затем начинать сложную операцию

2022-11-12 15:49 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = false
Рекомендую, использовать свойство [hidesWhenStopped](https://developer.apple.com/documentation/uikit/uiactivityindicatorview/1622837-hideswhenstopped) у activityIndicator вместо ручного управления isHidden

2022-11-12 15:49 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionFactory?.requestNextQuestion()
Ты можешь дополнительно показывать activityIndicator между загрузкой вопросов, потому что после загрузки фильмов, загрузка постера тоже занимает некоторое время из-за получения изображения.

2022-11-12 15:49 UTC, ABashkirova commented on MovieQuiz/Services/MovieLoader.swift
> +                guard let movies = try? JSONDecoder().decode(MostPopularMovies.self, from: data) else { return }
Здесь ошибка ветвления. 

Если сервис IMBDB поменяет свое API (например, переименует ключ items на movies), декодер не сможет распознать структуру и программа вызовет return в этой функции. Это значит что изначальный клиент(viewController) никогда не получит сообщение об ошибке. И будет крутить лоадер бесконечно. Приложение будет выглядеть зависнувшим. Будьте аккуратны с guard в функциях с completion-ом. 

Предлагаю провести эксперимент, переименовать у MostPopularMovies errorMessage на просто error. Запустить приложение и проверить что произойдет.

2022-11-12 15:49 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                print("Failed to load image")
Обращу внимание, что игра состоит из вопроса о рейтинге, на который отвечает пользователь, и контекста о фильме в виде постера. Без постера, пользователю будет затруднительно ответить на вопрос о рейтинге фильма верно.

В этом месте, функция не завершает свою работу и идет формировать вопрос без постера. В таком случае, бизнес-логика приложения будет нарушена, потому что пользователь не сможет ответить корректно. 

Это состояние стоит обработать, например, с помощью алерта. Не забудьте, что алерт будет обновлять UI и это тоже нужно учесть, ровно также, как и прерывание функции.

2022-11-12 15:49 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +
👍🏻

2022-11-12 15:49 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +        moviesLoader.loadMovies { result in
Контекст захватывается сильно. В данном приложении это не вызовет утечек, однако это потенциально будущая ошибка.
```suggestion
        moviesLoader.loadMovies { [weak self] result in
```

2022-11-13 14:23 UTC, SASHKEVICH commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = false
Надеюсь, что я правильно понял, как работать с этим свойством

2022-11-13 15:07 UTC, ABashkirova approved these changes
Замечания учтены, работа принята 🎉

2022-11-13 15:07 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> -        activityIndicator.isHidden = true
Да, тут верно убрал

можно еще  ` activityIndicator.isHidden = false` поубирать

2022-11-13 15:07 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                self.delegate?.didFailToLoadData(with: QuestionFactoryError.loadImage)
Тут надо проверить, не нужно ли обернуть на главную очередь:
```suggestion
                DispatchQueue.main.async { [weak self] in
                    self?.delegate?.didFailToLoadData(with: QuestionFactoryError.loadImage)
                }
```

2022-11-14 04:57 UTC, merged